language: python
dist: trusty
python: 3.5
env:
  - TOX_ENV=py26
  - TOX_ENV=py27
  - TOX_ENV=py27-pysnmp42
  - TOX_ENV=py33
  - TOX_ENV=py34
  - TOX_ENV=py35
  - TOX_ENV=py35-pysnmp42
  - TOX_ENV=py35-ipython
  - TOX_ENV=pypy-pysnmp42
  - TOX_ENV=lint
  - TOX_ENV=doc
install:
  - "sudo apt-get -y install pkg-config libsmi2-dev libsnmp-dev snmp-mibs-downloader ncurses-term"
  - pip install tox coveralls
before_script:
  - sudo sh -c 'echo 0 > /proc/sys/net/ipv6/conf/all/disable_ipv6'
script:
  - tox -e $TOX_ENV
after_success:
  - coveralls
